- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - role: ara-report
  ignore_errors: True
- hosts: 173.39.89.140
  gather_facts: False
  roles:
    - role: upload-logs
      zuul_log_url: "{{ logs_base_url }}"
  ignore_errors: True
- hosts: all
  roles:
    - role: add-authorized-keys
      public_keys:
        - public_key: "{{ debug_public_key }}"
      when: not zuul_success | bool
  ignore_errors: True
